apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: default
spec:
  encryptedData:
    github_token: AgABYZmJYWQpzcaMJtUwYF90MZFcg5LHYXY0CsDNRsyZuaSBJprlWkGcD4b1DwZHJMddDJckLYceAhGpRPbjy5siJ34oB8aiWL6viKs9XI/hQ+Bwo5KzpTUX37i2PAp2cq5vJJ9Xp9MzUj57hJBbwGnIq9os3mpCtL+LfjQstJE4KnPIUu00hmUNAvqCXF07IPnHXU/gF5LTHn/gNM/1ASFJFi0uCLf87ylJdbuQECT8lNmguwRqkQAH7Kn+vstmwvD+7D8a/yjzH8s6jlzH2xWNSs29gkcwVc0iJCqlngp8QgbFz/wnNaNNo/PudnfwCTh3ToDrM8icI7syVPJ7HE1pKewfp5G6Qk525H3M+nDfpRGasOPBYAbGuZ+Tw8bjN0xDFzH6muj0ioFbk7WtLvGKyjbzIh4VKsElh66hYz9erHaRmw8nIFxEYkXR+UF0xRU1AdpWSIJNw0hfv5AzK+x51DSAg6xy01T8L+7uzqmfyHDsmWfKiP+u3vL6bJKUnIWbpq+E76fr1YmuaxK6Z4+KxzDKUxxS7X9FcwgtfbQqlIu6ffbMooNOgtwcMU0a96NaCM2wQW5DjSpOUeOuIsSOnyOWDH/ND+2XVs7yBXQYcQ5xPbKgKPP6kO7vFTczm9NTZY2bj91a2KxR8NylM3AmLgXPria2q1V5LFulBsOsUAxI2CVoHDq7mITj1yBO+xomZFQEyo0r9oXkiEDOXzDik78LIeBJIiQb0BeEo3t2FNV7K88OSpzE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: default
