# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: force-adverse-runnerdeploy
spec:
  replicas: 1
  template:
    spec:
      organization: force-adverse
