---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii-mysql
  labels:
    app: firefly-iii
spec:
  selector:
    matchLabels:
      app: firefly-iii
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-iii
        tier: mysql
    spec:
      containers:
        - image: yobasystems/alpine-mariadb:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: firefly-iii-secrets
                  key: db_password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "1G"
              cpu: "500m"

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: data-firefly-iii-mysql
