---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-firefly-iii
  namespace: default
  labels:
    app: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-replicated
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-firefly-iii-mysql
  namespace: default
  labels:
    app: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-replicated
  resources:
    requests:
      storage: 10Gi
