# Service to expose Firefly-III on an available port in Kubernetes cluster
# Assigned port can be seen with `kubectl get services firefly-iii`

apiVersion: v1
kind: Service
metadata:
  name: firefly-iii
  labels:
    app: firefly-iii
spec:
  clusterIP: None
  ports:
    - port: 8080
  selector:
    app: firefly-iii
    tier: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: firefly-iii-mysql
  labels:
    app: firefly-iii
spec:
  ports:
    - port: 3306
  selector:
    app: firefly-iii
    tier: mysql
  clusterIP: None
