apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: default
spec:
  encryptedData:
    github_token: AgBtMkzel0cyL/Dtk8RFx0ufMNwxDfWZ+KgnKCzFpaEkCfDVRuYwT8ixFVhkIIz1TkyWXXG+Zc9Lr1mjsr1lW3SIy+bBC9klu/CdZx0HsGZ5TjEDxPhHHC7Ey3BcP1Ta0viQnN9yLVvIYu60OFpNr160WIV6DBqbLu33zpyiTYB5T8jOiKsR/9Ast+twoBgMRIjIK2meCUN3CIpP6wHYcNH2mlj1eCvpBTW/hJwQsmw9VcMPntVYvOVLzUofHRjUHvElaZfI5WqN2aLWg1ysvHzHjA5YYU0DIAJmyINPqHng9cQUJzXoBw2Gz8/XwDUhyEThoGUnrpFC39fvDK8dMcx9FIXWi+IPZUxMmM25CrkDclqsWfz6+FNjxxTrLsOKWE6s/l5IHEZHLRirbtPJoApHN4wU8ItM45mKybmpzIsDsnW1nyJpZKZYgHrFWc7g0kyhXiDM5jy5VLrJwOr/coXshDdjM4/KrrRkueOSwZhCq0QYqkwas5/6vMs6a8/WQTYFNpfz8H7b0TUESQ7NDaWfNbNBuBA8frY2iciRXISCq8JuxV9ZqLygvaOYC4q7POkfW3185L2Gy/grzLPd1AkI2LKBm73n6oE3Y9MJdzN7fUgvUHy8eqAMTeALNnKvHLoS0LHd0+KV9tZdWG4oLAIh2t2BFA9c5tLAAcAsm5LLaKfBMk6vwoUBLcO36t1ZiOplppvMgLto/Ga18Ib7BYaQp3G2tcwXIJuHfUMWjHCaKytv0bQ9x31m
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: default
